# Generated by Django 5.2.3 on 2025-06-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='answered_vocational_test',
            field=models.BooleanField(default=False),
        ),
    ]
