# Generated by Django 5.2.6 on 2025-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersession_answered_vocational_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='assistant_index',
        ),
        migrations.AddField(
            model_name='chat',
            name='input_tokens',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='openai_message_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='output_tokens',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
