# Generated by Django 5.2.6 on 2025-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usersession_assistant_index_chat_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chat',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
