# Generated by Django 5.2.6 on 2025-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chat_input_tokens_alter_chat_output_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='input_tokens',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='output_tokens',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
