# Generated by Django 5.2.6 on 2025-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chat_input_tokens_alter_chat_output_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='openai_message_id',
            field=models.TextField(null=True),
        ),
    ]
