# Generated by Django 5.2.6 on 2025-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chat_openai_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ai_model',
            field=models.TextField(null=True),
        ),
    ]
