# Generated by Django 5.2.6 on 2025-09-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chat_ai_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='answered_vocational_test',
        ),
        migrations.DeleteModel(
            name='VocationalTest',
        ),
    ]
