# Generated by Django 5.2.6 on 2025-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_usersession_answered_vocational_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
