services:
  postgres_db:
    restart: always
    image: postgres:latest
    container_name: postgres_descubra
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django_app:
    build: .
    container_name: django_descubra
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "${DJANGO_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"

volumes:
  db_data:
